name: Deploy to Kubernetes

on:
  workflow_run:
    workflows: ["Static Analysis"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

   # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubectl
      run: aws eks update-kubeconfig --name eks-proyectodevops --region ${{ secrets.AWS_REGION }}

    - name: Verify deployment YAML exists
      run: ls -l ./products-service-deployment.yaml

    - name: Deploy to Kubernetes
      run: kubectl apply -f ./products-service-deployment.yaml
