name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt-openjdk'

    - name: Build with Maven
      run: mvn clean package

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag products-service-example:$(date +%s)
    
    - name: Push Docker image to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
    - name: Push Docker image
      run: docker push products-service-example:$(date +%s)
