name: CI Pipeline

on:
  workflow_run:
    workflows: ["Static Analysis"]
    types:
      - completed

jobs:
  deploy:
    needs: []
    runs-on: ubuntu-latest  # Utilizar la última versión de Ubuntu para el runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Obtener el código del repositorio

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Utiliza el token de sesión si es necesario para tu configuración

    - name: Set up Kubernetes CLI
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'  # Puedes especificar una versión en lugar de 'latest' para asegurar la compatibilidad futura

    - name: Configure kubectl
      run: aws eks update-kubeconfig --name eks-proyectodevops --region ${{ secrets.AWS_REGION }}
      # Actualiza el archivo kubeconfig con la configuración del cluster EKS

    - name: Validate deployment YAML
      run: kubectl apply -f ./products-service-deployment.yaml --dry-run=client
      # Valida el archivo de despliegue antes de aplicarlo

    - name: Deploy to Kubernetes
      run: kubectl apply -f ./products-service-deployment.yaml
      # Aplica el archivo de despliegue a Kubernetes

    - name: Check deployment status
      run: kubectl rollout status deployment/products-service-deployment
      # Verifica el estado del despliegue
