name: Static Analysis

on:
  push:
    branches:
      - main  # Ejecutar el workflow cuando haya un push a la rama main
  pull_request:
    branches:
      - main  # Ejecutar el workflow para pull requests a la rama main

jobs:
  static-analysis:
    runs-on: ubuntu-latest  # Utilizar la última versión de Ubuntu para el runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Obtener el código del repositorio

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # Reemplaza con la versión de Node.js que necesitas

    - name: Install dependencies
      run: npm install
      # Instala las dependencias del proyecto

    - name: Set up SonarCloud
      uses: sonarsource/sonarcloud-github-action@v3
      with:
        organization: ${{ secrets.SONAR_ORGANIZATION }}
        token: ${{ secrets.SONAR_TOKEN }}
        projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
        projectName: ${{ secrets.SONAR_PROJECT_NAME }}

    - name: Run SonarCloud Analysis
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
   
